### ISSUE TITLE
Bad audio return if text has no punctuation

### ISSUE THREAD

**Issue by NeonDaniel** [NeonGeckoCom/neon-tts-plugin-mozilla_remote#8]
If there isn't terminating punctuation, the last phoneme is sometimes repeated for several seconds. Consider a generic method for adding punctuation as necessary, similar to <speak> tag handling

**Comment by NeonDaniel** [comment]
Consider patching in plugins too for Mycroft/OVOS compat

**Comment by JarbasAl** [comment]
hum, i think this makes sense to be handled on a case by case basis since its specific to each TTS engine. On the other hand i imagine this is a common problem, so adding some final punctuation could also be a good approach in OPM.

**Comment by NeonDaniel** [comment]
This is what I was thinking too.. The default TTS all works without punctuation, though I can't think of any reason a trailing '.' would break anything..
